services:
  nilulab:
    build: .
    image: nilulab:latest
    container_name: nilulab_app
    ports:
      - "8080:8080"
    volumes:
      - ./Qwen:/app/Qwen
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
