server.port=8080

# Max upload file size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Python executable (change if using a virtualenv)
python.executable=/home/mahyart/Desktop/github_repos/VLM/.venv/bin/python3
